language: java
jdk:
  - oraclejdk8

# https://github.com/travis-ci/travis-ci/issues/3259#issuecomment-130860338
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false